name: Python Bot CI and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.x environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # Adjust the Python version according to your project

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step 5: Checkout code for deployment
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 6: Deploy to Azure Web App using Publish Profile
      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

